version: '2'
services:
    autoreservation-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/autoreservation/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=autoreservation
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
